//
// Generated file, do not edit! Created by opp_msgc 4.1 from applications/dxps/../../tier2/xmlpsapp/Filter.msg.
//

#ifndef _FILTER_M_H_
#define _FILTER_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/dxps/../../tier2/xmlpsapp/Filter.msg</tt> by opp_msgc.
 * <pre>
 * packet Filter {
 * 
 *     unsigned char  filter[];
 *     int filterSize;
 * }
 * </pre>
 */
class Filter : public ::cPacket
{
  protected:
    unsigned char *filter_var; // array ptr
    unsigned int filter_arraysize;
    int filterSize_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Filter&);

  public:
    Filter(const char *name=NULL, int kind=0);
    Filter(const Filter& other);
    virtual ~Filter();
    Filter& operator=(const Filter& other);
    virtual Filter *dup() const {return new Filter(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setFilterArraySize(unsigned int size);
    virtual unsigned int getFilterArraySize() const;
    virtual unsigned char getFilter(unsigned int k) const;
    virtual void setFilter(unsigned int k, unsigned char filter_var);
    virtual int getFilterSize() const;
    virtual void setFilterSize(int filterSize_var);
};

inline void doPacking(cCommBuffer *b, Filter& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Filter& obj) {obj.parsimUnpack(b);}


#endif // _FILTER_M_H_
